### PR TITLE
Adds custom formatter

### PR DESCRIPTION
**Pull request by drahnieR**
Accepts a function formatter({level, message, meta}) in options. Which allows user to customize the mail body.

### CODE REVIEW

**Comment by wavded** [comment]
Thx @drahnieR, can you update the readme file with documentation on how to use?

**Comment by drahnieR** [comment]
Sure, PR updated.

**Comment by wavded** [comment]
Thx, merged.

**Comment by drahnieR** [comment]
Great!
Any idea when this is going be released?

**Comment by wavded** [comment]
Just released `1.2.0`

**Pull request merged**
