### PR TITLE
Updates for Winston 3.0

### PR DESCRIPTION
**Pull request by bcosma**
Changed log function for handle only 2 parameters: info, callback

### CODE REVIEW

**Comment by wavded** [comment]
This seems to be breaking change.  Winston also doesn't appear to be at version 3 yet (still in RC stage from a view of the README).  Perhaps we can make an API that allows both to work rather than cut ties with the older versions?

**Comment by bcosma** [comment]
@wavded indeed they are still in RC stage. I will think of a way to make this work for both 3.0 and older versions. Do you have any suggestion?

**Comment by wavded** [comment]
Perhaps we can check arity for the `log` function?  Or perhaps we can look up the version on the `winston` object itself if exposed.

**Comment by ericdrobinson** [comment]
What is the status on this? Is it close to being accepted and a new version pushed?

**Comment by wavded** [comment]
Sorry for the delay.  Thanks @bcosma, LGTM.  I'll merge it in an release shortly.

**Comment by wavded** [comment]
Released as `1.5.0`

**Pull request merged**
